### ISSUE TITLE
Activity diagrams

### ISSUE THREAD

**Issue by oliverbanks** [youngsang12/ISDM-Assignment-2#10]
To close this issue:

- Use use cases to create activity diagrams.

**Comment by youngsang12** [comment]
<img width="273" alt="스크린샷 2020-05-18 오후 1 58 16" src="https://user-images.githubusercontent.com/62223418/82173331-27886c80-9910-11ea-8999-d708b6460c5e.png">

**Comment by youngsang12** [comment]
As an end customer, I want to use the CMC to be served by RM's who have knowledge of my holiday packages so that they can help me plan new holidays and answer questions about purchased holidays.
<img width="340" alt="스크린샷 2020-05-18 오후 2 05 59" src="https://user-images.githubusercontent.com/62223418/82173489-c6ad6400-9910-11ea-9a2b-2498d4ccb82c.png">

**Comment by youngsang12** [comment]
<img width="322" alt="Activity diagram Travel company manager" src="https://user-images.githubusercontent.com/62223418/82188562-68dd4400-9931-11ea-882c-039c829f231f.png">

**Comment by youngsang12** [comment]
<img width="468" alt="Activity diagram Travel company manager" src="https://user-images.githubusercontent.com/62223418/82188626-7c88aa80-9931-11ea-927b-56324ea142e6.png">

**Comment by youngsang12** [comment]
<img width="459" alt="Activity diagram RM" src="https://user-images.githubusercontent.com/62223418/82188646-87433f80-9931-11ea-9441-89da4e8b99b2.png">

**Comment by oliverbanks** [comment]
@youngsang12 looking good! Could you please add them to the assignment document under the appropriate heading? https://github.com/youngsang12/ISDM-Assignment-2/blob/master/assignmentDocument.md
